---
# Docker repository
- name: Docker repo
  copy: 
    src: files/docker.list
    dest: /etc/apt/sources.list.d/docker.list

# GPG Key
- name: Docker signing key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

# Install package
- name: Install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

# Check for docker-compose
- name: Check to see if installed
  stat: path=/usr/local/bin/docker-compose
  register: docker_compose

# Install docker-compose
- name: Install Docker Compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/1.14.0/docker-compose-Linux-x86_64'
    dest: '/usr/local/bin/docker-compose'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: docker_compose.stat.exists == False

# Add user to docker group
- name: Adding  to docker group
  user: 
    name: "{{ user_name }}"
    groups: docker
    append: yes

