---
# Install Vagrant
- name: Check if vagrant is installed
  command: dpkg-query -l vagrant
  register: vagrant_installed
  failed_when: vagrant_installed.rc > 1

- name: Install vagrant
  apt:
    deb: https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.deb
  when: vagrant_installed.rc == 1

