---
# Virtualbox repository
- name: Virtualbox repo
  copy: 
    src: files/virtualbox.list
    dest: /etc/apt/sources.list.d/virtualbox.list

# GPG Key
- name: Virtualbox signing key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc state=present

# Install package
- name: Install virtualbox
  apt:
    name: virtualbox-5.1
    state: latest
    update_cache: yes

# Install Virtualbox extensions
- name: Check if extension pack is already installed
  shell: "VBoxManage list extpacks"
  register: extpack_list

- name: Download VirtualBox extension pack
  shell: "cd /tmp/ &&  wget http://download.virtualbox.org/virtualbox/5.1.26/Oracle_VM_VirtualBox_Extension_Pack-5.1.26-117224.vbox-extpack"
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: Install VirtualBox extension pack
  shell: "VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-5.1.26-117224.vbox-extpack --accept-license=715c7246dc0f779ceab39446812362b2f9bf64a55ed5d3a905f053cfab36da9e"
  when: 'extpack_list.stdout == "Extension Packs: 0"'

